-- Create contacts table
create table if not exists contacts (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  email text not null,
  phone text not null,
  country text not null,
  check_in date,
  check_out date,
  guests integer,
  room_type text,
  message text,
  action text not null default 'reservation',
  status text not null default 'pending'
);

-- Add RLS policies
alter table contacts enable row level security;

create policy "Enable read access for all users" on contacts
  for select using (true);

create policy "Enable insert access for all users" on contacts
  for insert with check (true);

create policy "Enable update access for authenticated users only" on contacts
  for update using (auth.role() = 'authenticated');

create policy "Enable delete access for authenticated users only" on contacts
  for delete using (auth.role() = 'authenticated'); 